### PR TITLE
Create about us page

### PR DESCRIPTION
**Pull request by roninlabs-teacher**
This is my first cut - would you mind adding the markup

### CODE REVIEW

**Comment by roninlabs-teacher** [comment]
Hey @peterbell - ping

**Comment by roninlabs-teacher** [comment]
This relates to issue #2

**Comment by roninlabs-teacher** [comment]
OK, I think this is good to go - what do you think @peterbell - should I merge this?

**Comment by roninlabs-teacher** [comment]
I agree @peterbell - that's way better - are we good to :shipit:?

**Comment by PeterBell** [comment]
Yup I'm ready - this gets a :+1: from me

**Comment by PeterBell** [comment]
harry-potter-congrats

**Comment by roninlabs-teacher** [comment]
Closes issue #2

**Pull request merged**
